#!/bin/bash

#  Sparky Repository Editor lets you edit repository lists
#  Created by Paweł "pavroo" Pijanowski 2014/05/22
#  Copyright 2014-2018 under the GNU GPL2 License
#  Last update 2018/03/16

testroot="`whoami`"
if [ "$testroot" != "root" ]; then
	echo "Must be root...Exiting..."
	exit 1
fi

if [ -f /usr/bin/sparky-editor ]; then
	SPARKYEDITOR="sparky-editor"
else
	SPARKYEDITOR="gnome-text-editor"
fi


$SPARKYEDITOR /etc/apt/sources.list

exit 0


